import { TradeSession, TradeDirection, EmotionalState, TradeLog } from './types';

export const STRATEGY_OPTIONS: string[] = [
  'Breakout',
  'Trend-Following',
  'News Trade',
  'Support/Resistance',
  'Scalping',
  'Swing Trading',
  'Midnight Open Strategy',
  'Daylight Open Strategy',
  'Candle Range Theory',
  'Other',
];

export const mockTradeData: TradeLog[] = [
  {
    id: 'mock1',
    entryDateTime: new Date('2023-10-26T09:30:00Z'),
    session: TradeSession.London,
    currencyPair: 'EUR/USD',
    direction: TradeDirection.Long,
    strategy: 'Breakout',
    pipsCaptured: 25,
    result: 'Win',
    riskFree: false,
    reason: 'Price broke above key resistance level with high volume. Waited for a retest which held as support before entering.',
    emotionalState: EmotionalState.Confident,
    suggestion: 'Trust the setup. Patience during the retest was key. Continue this disciplined approach.',
  },
  {
    id: 'mock2',
    entryDateTime: new Date('2023-10-26T14:15:00Z'),
    session: TradeSession.NewYork,
    currencyPair: 'GBP/JPY',
    direction: TradeDirection.Short,
    strategy: 'Trend-Following',
    pipsCaptured: -30,
    result: 'Loss',
    riskFree: false,
    reason: 'Entered short assuming the downtrend would continue, but a sudden news release caused a sharp reversal. Stop loss was hit.',
    emotionalState: EmotionalState.Rushed,
    suggestion: 'Always check the economic calendar before entering a trade, especially with volatile pairs. Avoid rushing entries near news events.',
  },
  {
    id: 'mock3',
    entryDateTime: new Date('2023-10-25T02:00:00Z'),
    session: TradeSession.Asia,
    currencyPair: 'AUD/USD',
    direction: TradeDirection.Long,
    strategy: 'Support/Resistance',
    pipsCaptured: 15,
    result: 'Win',
    riskFree: true,
    reason: 'Identified a strong support zone on the 4H chart. Price showed bullish divergence on the RSI before bouncing. Moved SL to BE after 10 pips.',
    emotionalState: EmotionalState.Calm,
    suggestion: 'Good use of multiple confluences (support zone, divergence). This high-probability setup worked well. Look for more like this.',
  },
];